// GENERATED by tools/generate-icons.py — DO NOT EDIT.
// Regenerate with: tools/generate-icons.sh
//
// The same `d` string is embedded in apps/web/public/favicon.svg;
// src/test/conventions.test.ts asserts the two have not drifted apart.
export const BRAND_MARK_PATH =
  'M5.20 5.50 L8.20 12.00 L5.20 18.50 L2.40 18.50 L5.40 12.00 L2.40 5.50 Z M12.96 6.67 L15.42 12.00 L12.96 17.33 L10.66 17.33 L13.12 12.00 L10.66 6.67 Z M19.67 7.84 L21.59 12.00 L19.67 16.16 L17.88 16.16 L19.80 12.00 L17.88 7.84 Z';
