#!/usr/bin/env python3
"""Generate every MyFleet icon artefact from one geometry table (FR-ICON-12).

Neither CI nor apps/web/Dockerfile runs this; every output is committed. Invoke
it through tools/generate-icons.sh when the mark changes.

The geometry table below — not favicon.svg — is the single source. The SVG is
itself an output, so hand-editing it will be overwritten (and is caught by
apps/web/src/test/conventions.test.ts, which pins favicon.svg against the
generated brandMarkPath.ts constant).
"""

from __future__ import annotations

import math
import pathlib

from PIL import Image, ImageDraw

# --- geometry ---------------------------------------------------------------
# Three right-pointing filled chevrons on a shared centreline, tapering in
# scale: a fleet in motion (design §8.1).
#
# Filled polygons rather than strokes. A fill downscales predictably, whereas a
# stroke's effective weight depends on how the rasteriser resolves stroke-width
# against a scaled viewBox — which is exactly the kind of drift that makes a
# 16px favicon turn to mush.
VIEWBOX = 24.0
CENTRE_Y = 12.0
HALF_HEIGHT = 6.5  # vertical half-extent of the largest chevron
ARM_RUN = 3.0      # horizontal run of each arm (steeper than 45 degrees, which
                   # buys the horizontal room for three chevrons plus real gaps)
THICKNESS = 2.8    # uniform horizontal thickness
SCALES = (1.0, 0.82, 0.64)
GAP = 2.46         # horizontal gap between successive chevrons
LEFT = 2.4         # cluster starts at the inner 80% of the canvas

MARK_LIGHT = '#020817'  # --foreground, against light browser chrome
MARK_DARK = '#f8fafc'   # near .dark's --foreground, against dark chrome
RASTER_BG = '#ffffff'   # opaque: iOS ignores transparency and composites onto
                        # black, which would erase a dark mark (FR-ICON-6)
SUPERSAMPLE = 4
MASKABLE_SAFE_RADIUS = 0.4 * VIEWBOX  # Android crops to an arbitrary shape

ROOT = pathlib.Path(__file__).resolve().parent.parent
PUBLIC = ROOT / 'apps' / 'web' / 'public'
BRAND_TS = ROOT / 'apps' / 'web' / 'src' / 'components' / 'brandMarkPath.ts'


def chevrons() -> list[list[tuple[float, float]]]:
    """Six vertices per chevron: the right-facing V, then its inner offset."""
    polys: list[list[tuple[float, float]]] = []
    x = LEFT
    for scale in SCALES:
        h, r, t = HALF_HEIGHT * scale, ARM_RUN * scale, THICKNESS * scale
        apex = x + r + t
        polys.append([
            (apex - r, CENTRE_Y - h),
            (apex, CENTRE_Y),
            (apex - r, CENTRE_Y + h),
            (apex - r - t, CENTRE_Y + h),
            (apex - t, CENTRE_Y),
            (apex - r - t, CENTRE_Y - h),
        ])
        x = apex + GAP
    return polys


POLYGONS = chevrons()


def path_data() -> str:
    return ' '.join(
        'M' + ' L'.join(f'{x:.2f} {y:.2f}' for x, y in poly) + ' Z'
        for poly in POLYGONS
    )


def maskable_shrink() -> float:
    """Scale that pulls every vertex inside the maskable safe circle.

    Computed rather than hardcoded so a geometry change cannot silently push the
    mark outside the safe zone and get it cropped on Android.
    """
    furthest = max(
        math.hypot(x - VIEWBOX / 2, y - VIEWBOX / 2)
        for poly in POLYGONS
        for x, y in poly
    )
    return min(1.0, MASKABLE_SAFE_RADIUS / furthest)


def raster(px: int, shrink: float = 1.0) -> Image.Image:
    img = Image.new('RGB', (px * SUPERSAMPLE, px * SUPERSAMPLE), RASTER_BG)
    draw = ImageDraw.Draw(img)
    k = px * SUPERSAMPLE / VIEWBOX
    c = VIEWBOX / 2
    for poly in POLYGONS:
        draw.polygon(
            [(((x - c) * shrink + c) * k, ((y - c) * shrink + c) * k) for x, y in poly],
            fill=MARK_LIGHT,
        )
    return img.resize((px, px), Image.LANCZOS)


SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
  <style>
    path {{ fill: {light}; }}
    @media (prefers-color-scheme: dark) {{ path {{ fill: {dark}; }} }}
  </style>
  <path d="{d}" />
</svg>
"""

TS = """// GENERATED by tools/generate-icons.py — DO NOT EDIT.
// Regenerate with: tools/generate-icons.sh
//
// The same `d` string is embedded in apps/web/public/favicon.svg;
// src/test/conventions.test.ts asserts the two have not drifted apart.
export const BRAND_MARK_PATH =
  '{d}';
"""


def main() -> None:
    PUBLIC.mkdir(parents=True, exist_ok=True)
    d = path_data()

    (PUBLIC / 'favicon.svg').write_text(SVG.format(light=MARK_LIGHT, dark=MARK_DARK, d=d))
    BRAND_TS.write_text(TS.format(d=d))

    raster(180).save(PUBLIC / 'apple-touch-icon.png')
    raster(192).save(PUBLIC / 'icon-192.png')
    raster(512).save(PUBLIC / 'icon-512.png')
    raster(512, maskable_shrink()).save(PUBLIC / 'icon-512-maskable.png')
    # Rendered at 64 so Pillow downsamples cleanly into both ICO entries.
    raster(64).save(PUBLIC / 'favicon.ico', sizes=[(16, 16), (32, 32)])

    # Only the icon files the budget (FR-PERF-4) is about — not every file that
    # happens to live in apps/web/public/ (site.webmanifest today, anything
    # else dropped in there later).
    ICON_NAMES = (
        'favicon.svg',
        'favicon.ico',
        'apple-touch-icon.png',
        'icon-192.png',
        'icon-512.png',
        'icon-512-maskable.png',
    )
    total = sum((PUBLIC / name).stat().st_size for name in ICON_NAMES)
    print(f'generate-icons: wrote {PUBLIC} ({total / 1024:.1f} KiB total)')
    if total > 100 * 1024:
        raise SystemExit('generate-icons: FAIL — assets exceed the 100 KB budget (FR-PERF-4)')


if __name__ == '__main__':
    main()
